### ISSUE TITLE
License activation strategy could not be determined

### ISSUE THREAD

**Issue by Bdoom** [webbertakken/unity-actions#65] opened 2020-05-05 18:53 UTC
https://i.imgur.com/10NEAi7.png

**Comment by Bdoom** [comment] 2020-05-05 18:53
I just want my stuff to work for my local master repository. Here is my config:
name: Build project

on:
  pull_request: {}
  push: { branches: [master] }
  
jobs:
  buildForSomePlatforms:
    name: Build for ${{ matrix.targetPlatform }} on version ${{ matrix.unityVersion }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        projectPath:
          - /
        unityVersion:
          - 2019.2.11f1
          - 2019.3.0f1
        targetPlatform:
          - StandaloneOSX # Build a macOS standalone (Intel 64-bit).
          - StandaloneWindows # Build a Windows standalone.
          - StandaloneWindows64 # Build a Windows 64-bit standalone.
          - StandaloneLinux64 # Build a Linux 64-bit standalone.
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: actions/cache@v1.1.0
        with:
          path: ${{ matrix.projectPath }}/Library
          key: Library-${{ matrix.projectPath }}-${{ matrix.targetPlatform }}
          restore-keys: |
            Library-${{ matrix.projectPath }}-
            Library-
      - uses: webbertakken/unity-builder@v0.11
        with:
          projectPath: ${{ matrix.projectPath }}
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}
      - uses: actions/upload-artifact@v1
        with:
          name: Build
          path: build

**Comment by webbertakken** [comment] 2020-05-05 18:59
Hi @Bdoom, and thank you for sending your report.

To make everyone's life easier, could you please properly format your code and tell us what you tried to do to fix the problem? 

Thank you.

**Comment by Bdoom** [comment] 2020-05-05 19:01
```
name: Build project

on:
  pull_request: {}
  push: { branches: [master] }
  
jobs:
  buildForSomePlatforms:
    name: Build for ${{ matrix.targetPlatform }} on version ${{ matrix.unityVersion }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        projectPath:
          - /
        unityVersion:
          - 2019.2.11f1
          - 2019.3.0f1
        targetPlatform:
          - StandaloneOSX # Build a macOS standalone (Intel 64-bit).
          - StandaloneWindows # Build a Windows standalone.
          - StandaloneWindows64 # Build a Windows 64-bit standalone.
          - StandaloneLinux64 # Build a Linux 64-bit standalone.
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: actions/cache@v1.1.0
        with:
          path: ${{ matrix.projectPath }}/Library
          key: Library-${{ matrix.projectPath }}-${{ matrix.targetPlatform }}
          restore-keys: |
            Library-${{ matrix.projectPath }}-
            Library-
      - uses: webbertakken/unity-builder@v0.11
        with:
          projectPath: ${{ matrix.projectPath }}
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}
      - uses: actions/upload-artifact@v1
        with:
          name: Build
          path: build

```

**Comment by Bdoom** [comment] 2020-05-05 19:01
Does this look better? :)

**Comment by webbertakken** [comment] 2020-05-05 19:08
You're certainly showing great patience and very thorough research about why your problem occurs. It's sounds very thankful towards the people that put in countless of hours to make this available for you 😉

Please note that your project path is currently set to the absolute root, rather than the root of your project. You may want to try changing 

```yaml
        projectPath:
          - /
```

to 
```yaml
        projectPath:
          - .
```

or rather leave it at the default.

**Comment by Bdoom** [comment] 2020-05-05 19:14
I'm sorry for being lazy and not fully reading the guide. I am still having this afterwards:

`##[error]The process '/usr/bin/docker' failed with exit code 1`

I am using a "personal" license and I'm just wondering if there are any examples on how to do this with a personal license? I read something about getting a manual license file?

**Comment by webbertakken** [comment] 2020-05-05 19:19
Sure!

To get a valid license, you need to request an activation file on github.

See request activation file example: https://github.com/webbertakken/unity-request-manual-activation-file#usage
And be sure to follow it up with the activation steps right below that example.

Rest of the workflow:

Simple example: https://github.com/webbertakken/unity-actions#simple-example
Advanced example: https://github.com/webbertakken/unity-actions#advanced-example

**Comment by Bdoom** [comment] 2020-05-05 19:29
```
 ###########################
#    Building platform    #
###########################

Initiating legacy licensing module

LICENSE SYSTEM [202055 15:26:0] Next license update check is after 2020-05-06T19:20:58


LICENSE SYSTEM [202055 15:26:0] d39b8e2f4d364b2e98b06afa0c6e08c5 != 00330-80000-00000-AA307


LICENSE SYSTEM [202055 15:26:0] d39b8e2f4d364b2e98b06afa0c6e08c5 != W -DCW3C1F032506

DisplayProgressbar: Unity license
[UnityConnectServicesConfig] config is NOT valid, switching to default
[0505/152601:ERROR:browser_main_loop.cc(161)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
[0505/152601:ERROR:sandbox_linux.cc(308)] InitializeSandbox() called with multiple threads in process gpu-process

Very cool. Okay, so I got the key setup, and I added it back in the script under env: 

I also tried to run it again but got the error mentioned above. In my script, it seems like it's not recognizing my file. The guide says that we should simply copy the entire file contents of the .ulf file. Which I copied into my "SECRETS" on my repository. Is this the correct method? It looks like the license file is simply an xml file. Is that right? Is it possible that these licenses cannot be used on both my machine, and the script?

```

**Comment by Bdoom** [comment] 2020-05-05 20:29
Do you happen to know what this is caused by:

`Cancelling DisplayDialog: Failed to activate/update license. Missing or bad username and password. Please try again using valid credentials or contact support@unity3d.com`

I already had it working once, but then I run it again and it doesnt work? Can the license only be used once?

**Comment by Bdoom** [comment] 2020-05-05 20:43
![image](https://user-images.githubusercontent.com/1284431/81114171-8224d000-8eef-11ea-951c-b9c4a76b3529.png)


Looks like it's all working, but for some unknown reason Unity seems to not be including all my  files?

If I build it regularly, outside of Unity-actions it compiles fine. So I'm wondering if you may have seen this before?

**Comment by Bdoom** [comment] 2020-05-05 20:55
Also, are all versions of unity supported? We are us ing 2019.2.5f1

**Comment by webbertakken** [comment] 2020-05-06 14:49
The initial issue, and several issues thereafter seem to have been solved. I'm closing this ticket because there errors don't look related to Unity Actions.

Feel free to open a new issue if you have any specific issue that you didn't manage to solve by yourself. Be sure to add enough detail about why the problem is happening, so the community can help you out.

**Closed by webbertakken** 2020-05-06 14:49 UTC
