### ISSUE TITLE
Personal license activation issue, apparently due to change in docker image used (specific versions)

### ISSUE THREAD

**Issue by LucidDan** [webbertakken/unity-actions#70] opened 2020-05-28 07:18 UTC
**Describe the bug**

I originally posted this on another issue then realised the symptoms are slightly different. However, I've seen a few issues that sound similar enough that they could be related to this.

The issue I've been having is trying to get 2019.2.2f1 working, with a personal license using the method described in the documentation to activate. Reproduction config and output below, as well as the workaround I've found to fix the issue.

**To Reproduce**
- Config as below for workflow.
- Run activation workflow to get a license file (ALF)
- Go to unity manual activation page (https://license.unity3d.com/manual), sign in, and submit the ALF.
- Get back a license (ULF).
- Load the license as a secret in the GitHub repository.
- Run the unity build workflow to build the unity project.

Activation workflow to reproduce:
```
name: Acquire license
on: [push]
jobs:
  acquire:
    name: Request ALF file for manual license
    runs-on: ubuntu-latest
    steps:
    - name: Request manual activation file
      id: getManualLicenseFile
      uses: webbertakken/unity-request-manual-activation-file@v1.1
      with:
        unityVersion: 2019.2.2f1
    - name: Expose as artifact
      uses: actions/upload-artifact@v1
      with:
        name: ${{ steps.getManualLicenseFile.outputs.filePath }}
        path: ${{ steps.getManualLicenseFile.outputs.filePath }}
```

Build workflow to reproduce:
```
name: Build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  build-unitybundle:
    name: Build Unity Asset Bundles
    runs-on: ubuntu-latest
    steps:
    # Checkout
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        lfs: true
    # Cache
    - name: Cache
      uses: actions/cache@v1.1.0
      with:
        path: |
          unity/Library
        key: Library-Unity-KSP
    # Build
    - name: Build project
      uses: webbertakken/unity-builder@v1.0
      with:
        projectPath: unity
        unityVersion: 2019.2.2f1
        targetPlatform: StandaloneWindows
        buildMethod: AssetBundleBuilder.RunAssetBuild
    # Output 
    - uses: actions/upload-artifact@v1
      with:
        name: AssetBundle
        path: GameData
```

**Expected behavior**
Expected the license to be activated and build step proceeding from there.

**Screenshots**
Log output during build step:
```
Initiating legacy licensing module

LICENSE SYSTEM [2020527 23:35:47] Next license update check is after 2020-05-29T02:53:36


LICENSE SYSTEM [2020527 23:35:47] ec8c412afd074a7fac53f299632627bb != d39b8e2f4d364b2e98b06afa0c6e08c5


LICENSE SYSTEM [2020527 23:35:47] ec8c412afd074a7fac53f299632627bb != d39b8e2f4d364b2e98b06afa0c6e08c5

DisplayProgressbar: Unity license
[UnityConnectServicesConfig] config is NOT valid, switching to default
[0527/233548:ERROR:browser_main_loop.cc(161)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
[0527/233548:ERROR:sandbox_linux.cc(308)] InitializeSandbox() called with multiple threads in process gpu-process
Cancelling DisplayDialog: Failed to activate/update license. Missing or bad username and password. Please try again using valid credentials or contact support@unity3d.com
This should not be called in batch mode.
 
(Filename: ./Editor/Platform/Linux/EditorUtility.cpp Line: 274)

Build failed, with exit code 1
```

**Additional context**

What I've found is that I can work around this issue if I run the activation workflow with the following configuration:
```
name: Acquire license
on: [push]
jobs:
  acquire:
    name: Request ALF file for manual license
    runs-on: ubuntu-latest
    steps:
    - name: Request manual activation file
      id: getManualLicenseFile
      uses: webbertakken/unity-request-manual-activation-file@v1.1
      with:
        # CHANGE: Add -windows, causes it to use the correct/same docker image as for build step
        unityVersion: 2019.2.2f1-windows
    - name: Expose as artifact
      uses: actions/upload-artifact@v1
      with:
        # CHANGE: Use hard-coded filename because unity-request-manual-activation returns "Unity_v2019.2.2f1-windows.alf" as the output.
        name: Unity_v2019.2.2f1.alf
        path: Unity_v2019.2.2f1.alf
```

**Comment by LucidDan** [comment] 2020-05-28 07:22
Based on the workaround and my investigation - it seems like what is happening is the unity-request-activation-file action is using gableroux/unity3d:2019.2.2f1, but the unity-builder is using gableroux/unity3d:2019.2.2f1-windows. The docker images are different and Unity expects a different "Machine binding" value, hence the error about:
```
LICENSE SYSTEM [2020527 23:35:47] ec8c412afd074a7fac53f299632627bb != d39b8e2f4d364b2e98b06afa0c6e08c5
```

When I run gableroux's images locally on my machine, if I produce a license activation file (ALF) using unity3d:2019.2.2f1, and try to activate that license in unity3d:2019.2.2f1-windows, I get *exactly* the same error.

**Comment by webbertakken** [comment] 2020-05-28 08:15
@LucidDan Thank you for reporting this issue and especially for providing proper steps to reproduce! This really helps a lot with determining the cause. 

Activating with the generic image is `acquire-manual-activation-file` is as intended and for most versions works as expected (see also the workflow in this repo which uses multiple different images. 

Unfortunaly we don't know the exact criteria for the "machine binding" beyond unity version and hardware fingerprint (if any). Possibly this is just a bug in Unity itself or perhaps (@GabLeRoux) there's a mismatch between the windows image and the generic image for 2019.2.2f1 that is different from the other images.

In the meantime, as a workaround I can confirm this issue with exactly the same steps to reproduce does not occur with 2019.2.11f1 and 2019.3.8f1.

**Comment by webbertakken** [comment] 2020-06-02 21:31
It looks like specific (especially bleeding edge versions) of unity sometimes encounter regressions in the licensing module.

There is nothing we can do, except keep a list of the specific versions that face this exact issue.

So far we've seen:

- 2019.3.14f1
- 2020.1.0b1
- 2020.1.0b9
- possibly other images with `b` in their version name (we [think](https://github.com/webbertakken/unity-actions/issues/66) these are beta builds)

Closing this issue as there is nothing to do from our side.

**Closed by webbertakken** 2020-06-02 21:31 UTC
Labels: bug in unity, wontfix

**Comment by webbertakken** [comment] 2021-04-23 22:15
See also https://github.com/game-ci/unity-actions/issues/84
