### ISSUE TITLE
Fallback handler could not load library. invalid ELF header.

### ISSUE THREAD

**Issue by gblikas** [webbertakken/unity-actions#41] opened 2020-01-28 01:52 UTC
I have a few native libraries I load into my Unity project, and it seems to me that the Unity install provided through your Docker instance is defaulting Unity to a 32 bit version?... Not sure if this is correct, but an objdump of my native libraries shows them as 

```
file format elf64-x86-64
```

Am I correct in assuming that I should just build out 32 bit versions? If so, easy support for 64 bit systems should be default, or at least _very_ easy to switch to.

**Comment by webbertakken** [comment] 2020-01-28 06:58
@GabLeRoux could you pitch in to this one?

Is this correct? and what would we have to do to support this?

**Comment by GabLeRoux** [comment] 2020-01-28 13:13
yep, I was on my mobile yesterday and didn’t have enough battery to answer ;)

Are we talking about the unity editor binary that is not running as 64bit? Or are we talking about resulting linux artifacts that are 32bit?

**Comment by gblikas** [comment] 2020-01-28 17:27
@GabLeRoux The former, I believe. I am using the default image via , https://github.com/webbertakken/unity-actions, which is resulting in, what I believe is, a Unity Editor binary that is running as 32 bit: 

```
jobs:
          
  requestActivationAndRunTests:
    name: Request Active Liscene and Run Tests
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v1

      # Activate Unity
      - name: Unity - Activate
        uses: webbertakken/unity-activate@v1
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

      - name: Run tests
        id: testRunner
        uses: webbertakken/unity-test-runner@v1.1
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          TEST_MODE: all

      - name: Expose as artifact
        uses: actions/upload-artifact@v1
        with:
          name: Test Results AllModes
          path: ${{ steps.testRunner.outputs.artifactsPath }}
```

When the `webbertakken/unity-test-runner@v1.1` action runs, I get a 
```
Fallback handler could not load library <name> 
// ...
Plugins: Couldn't open Assets/Plugins/x86_64/<name> 
//...
<name>.so invalid ELF header
```

However, an `objdump -h <name>.so` shows that the file format of my library is `file format elf64-x86-64`. The only "strange" flag I built my library with is `-fPIC`, however, I doubt that would cause this problem.

**Comment by gblikas** [comment] 2020-01-29 17:52
@webbertakken @GabLeRoux Did some more testing, by install the latest Ubuntu on my VirtualBox, [installing UnityHub](https://forum.unity.com/threads/unity-hub-v2-0-0-release.677485/?_ga=2.91015258.1568454044.1580163787-28725382.1574720498), and the latest Unity 2019.2.19f1, and pulling my repository-- I **did NOT** get a message like the following, when trying to load (run) my native libraries (tests): 

```
Fallback handler could not load library <name> 
// ...
Plugins: Couldn't open Assets/Plugins/x86_64/<name> 
//...
<name>.so invalid ELF header
```
I am leaning on the host VM not being 64 bit... absolute shot in the dark tho.

**Comment by webbertakken** [comment] 2020-01-29 18:45
Sorry but you're making many assumptions without any basis for it.

Github Actions architecture runs on the following specs:

Processors: [source](https://docs.microsoft.com/en-us/azure/virtual-machines/windows/sizes-general#dsv2-series)

- Intel® Xeon® 8171M 2.1GHz (Skylake)
- Intel® Xeon® E5-2673 v4 2.3 GHz (Broadwell)
- Intel® Xeon® E5-2673 v3 2.4 GHz (Haswell)

Operating systems: [source](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/virtual-environments-for-github-hosted-runners#supported-runners-and-hardware-resources)

- Windows Server 2019
- Ubuntu 18.04
- Ubuntu 16.04
- MacOS 10.15

In our case we're running Ubuntu 18.04 (which doesn't come in a 32-bit version; [source](https://wiki.ubuntu.com/ArtfulAardvark/ReleaseNotes))

Note that this effectively proves that docker is run on 64-bit.

About the images: 

- Ubuntu - version 18.04 (again, doesn't come in 32-bit version)
- Unity - version 2019.2.11f1 (unity stopped making `32-bit` builds since `2017.1.0` [source](https://unity3d.com/unity/whats-new/unity-2017.1.0))

What am I missing?

**Comment by webbertakken** [comment] 2020-02-01 12:47
@gblikas have you made any progress on this one?

**Comment by webbertakken** [comment] 2020-02-01 18:58
Closing this until there are actual steps to reproduce this. 

For all we know this is a platform mismatch, which requires the libraries to be built on the same platform as where unity is ran.

**Closed by webbertakken** 2020-02-01 18:58 UTC
Labels: need steps to reproduce
